name: Project Wallace CSS Diff

on: pull_request

jobs:
  cssDiff:
    name: Comment CSS Diff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Combine CSS
        run: cat _includes/*.css > all.css
      - name: Project Wallace Diff
        uses: projectwallace/css-diff-action@master
        with:
          project-wallace-token: ${{ secrets.PROJECT_WALLACE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          css-path: ./all.css
