name: CSS Workflow

on: pull_request

jobs:
  cssDiff:
    name: Comment CSS Diff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Project Wallace Diff
        uses: projectwallace/css-diff-action@master
        with:
          project-wallace-token: ${{ secrets.PROJECT_WALLACE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          css-path: ./_includes/style.css
